In [3]:
import json

with open("../data/raw/shl_catalog.json", "r", encoding="utf-8") as f:
    data = json.load(f)

print("Number of assessments:", len(data))

Number of assessments: 377

In [4]:
data[0]

{'entity_id': '4302',
 'name': 'Global Skills Development Report',
 'link': 'https://www.shl.com/products/product-catalog/view/global-skills-development-report/',
 'scraped_at': '2026-05-08T10:40:21.464836+00:00',
 'job_levels': ['Director',
  'Entry-Level',
  'Executive',
  'General Population',
  'Graduate',
  'Manager',
  'Mid-Professional',
  'Front Line Manager',
  'Supervisor'],
 'job_levels_raw': 'Director, Entry-Level, Executive, General Population, Graduate, Manager, Mid-Professional, Front Line Manager, Supervisor,',
 'languages': [],
 'languages_raw': '',
 'duration': '',
 'duration_raw': '',
 'status': 'ok',
 'remote': 'yes',
 'adaptive': 'no',
 'description': 'This report is designed to be given to individuals who have completed the Global Skills Assessment (GSA). With coverage across the Great 8 Domains, this measure of self-reported behaviors offers a complete overview of their current skills. Participants receive actionable tips on leveraging their top skill strengths and how they might develop their growth skills.',
 'keys': ['Ability & Aptitude',
  'Assessment Exercises',
  'Biodata & Situational Judgment',
  'Competencies',
  'Development & 360',
  'Personality & Behavior']}

In [5]:
data[0].keys()

dict_keys(['entity_id', 'name', 'link', 'scraped_at', 'job_levels', 'job_levels_raw', 'languages', 'languages_raw', 'duration', 'duration_raw', 'status', 'remote', 'adaptive', 'description', 'keys'])

In [6]:
import pandas as pd

df = pd.DataFrame(data)

df.head()

,entity_id,name,link,scraped_at,job_levels,job_levels_raw,languages,languages_raw,duration,duration_raw,status,remote,adaptive,description,keys
0,4302,Global Skills Development Report,https://www.shl.com/products/product-catalog/v...,2026-05-08T10:40:21.464836+00:00,"[Director, Entry-Level, Executive, General Pop...","Director, Entry-Level, Executive, General Popu...",[],,,,ok,yes,no,This report is designed to be given to individ...,"[Ability & Aptitude, Assessment Exercises, Bio..."
1,3827,.NET Framework 4.5,https://www.shl.com/products/product-catalog/v...,2026-05-08T10:39:46.810448+00:00,"[Professional Individual Contributor, Mid-Prof...","Professional Individual Contributor, Mid-Profe...",[English (USA)],"English (USA),",30 minutes,Approximate Completion Time in minutes = 30,ok,yes,yes,The.NET Framework 4.5 test measures knowledge ...,[Knowledge & Skills]
2,4094,.NET MVC (New),https://www.shl.com/products/product-catalog/v...,2026-05-08T10:39:53.276083+00:00,"[Mid-Professional, Professional Individual Con...","Mid-Professional, Professional Individual Cont...",[English (USA)],"English (USA),",17 minutes,Approximate Completion Time in minutes = 17,ok,yes,no,Multi-choice test that measures the knowledge ...,[Knowledge & Skills]
3,4099,.NET MVVM (New),https://www.shl.com/products/product-catalog/v...,2026-05-08T10:41:53.047159+00:00,"[Mid-Professional, Professional Individual Con...","Mid-Professional, Professional Individual Cont...",[English (USA)],"English (USA),",5 minutes,Approximate Completion Time in minutes = 5,ok,yes,no,Multi-choice test that measures the knowledge ...,[Knowledge & Skills]
4,4018,.NET WCF (New),https://www.shl.com/products/product-catalog/v...,2026-05-08T10:41:58.935422+00:00,"[Mid-Professional, Professional Individual Con...","Mid-Professional, Professional Individual Cont...",[English (USA)],"English (USA),",11 minutes,Approximate Completion Time in minutes = 11,ok,yes,no,Multi-choice test that measures the knowledge ...,[Knowledge & Skills]

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 377 entries, 0 to 376
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   entity_id       377 non-null    str
 1   name            377 non-null    str
 2   link            377 non-null    str
 3   scraped_at      377 non-null    str
 4   job_levels      377 non-null    object
 5   job_levels_raw  377 non-null    str
 6   languages       377 non-null    object
 7   languages_raw   377 non-null    str
 8   duration        377 non-null    str
 9   duration_raw    377 non-null    str
 10  status          377 non-null    str
 11  remote          377 non-null    str
 12  adaptive        377 non-null    str
 13  description     377 non-null    str
 14  keys            377 non-null    object
dtypes: object(3), str(12)
memory usage: 44.3+ KB

In [8]:
df.isnull().sum()

entity_id         0
name              0
link              0
scraped_at        0
job_levels        0
job_levels_raw    0
languages         0
languages_raw     0
duration          0
duration_raw      0
status            0
remote            0
adaptive          0
description       0
keys              0
dtype: int64

In [9]:
for column in df.columns:
    empty = (df[column] == "").sum()
    print(f"{column}: {empty}")

entity_id: 0
name: 0
link: 0
scraped_at: 0
job_levels: 0
job_levels_raw: 19
languages: 0
languages_raw: 37
duration: 61
duration_raw: 62
status: 0
remote: 0
adaptive: 0
description: 0
keys: 0

In [10]:
df["entity_id"].duplicated().sum()

np.int64(0)

In [11]:
df["name"].duplicated().sum()

np.int64(0)

In [12]:
df["link"].duplicated().sum()

np.int64(0)

In [13]:
import pandas as pd

normalized_df = df.copy()

In [14]:
normalized_df["remote"] = (
    normalized_df["remote"]
    .str.lower()
    .map({"yes": True, "no": False})
)

normalized_df["adaptive"] = (
    normalized_df["adaptive"]
    .str.lower()
    .map({"yes": True, "no": False})
)

In [15]:
normalized_df[["remote","adaptive"]].head()

   remote  adaptive
0    True     False
1    True      True
2    True     False
3    True     False
4    True     False

In [16]:
import re

def extract_minutes(text):

    match = re.search(r"\d+", str(text))

    if match:
        return int(match.group())

    return None

normalized_df["duration_minutes"] = normalized_df["duration"].apply(extract_minutes)

In [17]:
normalized_df[
["duration","duration_minutes"]
].head()

     duration  duration_minutes
0                           NaN
1  30 minutes              30.0
2  17 minutes              17.0
3   5 minutes               5.0
4  11 minutes              11.0

In [18]:
list_columns = [
    "job_levels",
    "languages",
    "keys"
]

for col in list_columns:

    normalized_df[col] = normalized_df[col].apply(
        lambda x: x if isinstance(x,list) else []
    )

In [19]:
columns_to_remove = [

    "scraped_at",

    "duration_raw",

    "languages_raw",

    "job_levels_raw",

    "status"

]

normalized_df = normalized_df.drop(
    columns=columns_to_remove
)

In [20]:
def build_search_text(row):

    return f"""
Assessment Name:
{row['name']}

Description:
{row['description']}

Categories:
{', '.join(row['keys'])}

Job Levels:
{', '.join(row['job_levels'])}

Languages:
{', '.join(row['languages'])}

Duration:
{row['duration']}

Remote:
{row['remote']}

Adaptive:
{row['adaptive']}
""".strip()

In [21]:
normalized_df["search_text"] = normalized_df.apply(
    build_search_text,
    axis=1
)

In [22]:
print(
normalized_df.iloc[0]["search_text"]
)

Assessment Name:
Global Skills Development Report

Description:
This report is designed to be given to individuals who have completed the Global Skills Assessment (GSA). With coverage across the Great 8 Domains, this measure of self-reported behaviors offers a complete overview of their current skills. Participants receive actionable tips on leveraging their top skill strengths and how they might develop their growth skills.

Categories:
Ability & Aptitude, Assessment Exercises, Biodata & Situational Judgment, Competencies, Development & 360, Personality & Behavior

Job Levels:
Director, Entry-Level, Executive, General Population, Graduate, Manager, Mid-Professional, Front Line Manager, Supervisor

Languages:


Duration:


Remote:
True

Adaptive:
False

In [23]:
def build_metadata(row):

    return {

        "entity_id": row["entity_id"],

        "name": row["name"],

        "url": row["link"],

        "duration": row["duration_minutes"],

        "remote": row["remote"],

        "adaptive": row["adaptive"],

        "job_levels": row["job_levels"],

        "languages": row["languages"],

        "categories": row["keys"]

    }

In [24]:
normalized_df["metadata"] = normalized_df.apply(
    build_metadata,
    axis=1
)

In [25]:
normalized_df["metadata"][0]

{'entity_id': '4302',
 'name': 'Global Skills Development Report',
 'url': 'https://www.shl.com/products/product-catalog/view/global-skills-development-report/',
 'duration': nan,
 'remote': True,
 'adaptive': False,
 'job_levels': ['Director',
  'Entry-Level',
  'Executive',
  'General Population',
  'Graduate',
  'Manager',
  'Mid-Professional',
  'Front Line Manager',
  'Supervisor'],
 'languages': [],
 'categories': ['Ability & Aptitude',
  'Assessment Exercises',
  'Biodata & Situational Judgment',
  'Competencies',
  'Development & 360',
  'Personality & Behavior']}

In [26]:
required_columns = [

    "entity_id",

    "name",

    "link",

    "description",

    "search_text"

]

In [27]:
for col in required_columns:

    missing = normalized_df[col].isnull().sum()

    print(col, missing)

entity_id 0
name 0
link 0
description 0
search_text 0

In [28]:
empty_descriptions = normalized_df[
    normalized_df["description"].str.strip() == ""
]

print(len(empty_descriptions))

0

In [29]:
empty_search = normalized_df[
    normalized_df["search_text"].str.strip() == ""
]

print(len(empty_search))

0

In [30]:
invalid = normalized_df[
~normalized_df["link"].str.startswith("https://")
]

print(len(invalid))

0

In [31]:
normalized_df.to_json(

    "../data/processed/knowledge_base.json",

    orient="records",

    indent=4
)

In [32]:
normalized_df.to_csv(

    "../data/processed/knowledge_base.csv",

    index=False
)

In [33]:
documents = pd.DataFrame()

In [34]:
documents["id"] = normalized_df["entity_id"]

In [35]:
documents["text"] = normalized_df["search_text"]

In [36]:
def create_metadata(row):

    return {

        "name": row["name"],

        "url": row["link"],

        "duration": row["duration_minutes"],

        "remote": row["remote"],

        "adaptive": row["adaptive"],

        "job_levels": row["job_levels"],

        "languages": row["languages"],

        "categories": row["keys"]

    }

In [37]:
documents["metadata"] = normalized_df.apply(
    create_metadata,
    axis=1
)

In [38]:
documents.iloc[0]

id                                                       4302
text        Assessment Name:\nGlobal Skills Development Re...
metadata    {'name': 'Global Skills Development Report', '...
Name: 0, dtype: object

In [39]:
documents.to_json(

    "../data/processed/documents.json",

    orient="records",

    indent=4
)

In [40]:
from collections import Counter

category_counter = Counter()

for categories in normalized_df["keys"]:
    category_counter.update(categories)

print(category_counter)

Counter({'Knowledge & Skills': 240, 'Personality & Behavior': 67, 'Simulations': 43, 'Ability & Aptitude': 32, 'Competencies': 19, 'Biodata & Situational Judgment': 17, 'Development & 360': 7, 'Assessment Exercises': 2})

In [41]:
job_counter = Counter()

for levels in normalized_df["job_levels"]:
    job_counter.update(levels)

print(job_counter)

Counter({'Mid-Professional': 304, 'Professional Individual Contributor': 296, 'Graduate': 140, 'Manager': 117, 'Entry-Level': 114, 'Front Line Manager': 75, 'Supervisor': 73, 'Director': 55, 'Executive': 55, 'General Population': 45})

In [42]:
language_counter = Counter()

for langs in normalized_df["languages"]:
    language_counter.update(langs)

print(language_counter)

Counter({'English (USA)': 321, 'English International': 74, 'Latin American Spanish': 51, 'French': 50, 'Italian': 47, 'Dutch': 45, 'Chinese Simplified': 45, 'German': 41, 'French (Canada)': 37, 'Portuguese (Brazil)': 37, 'Finnish': 37, 'Danish': 36, 'Swedish': 35, 'Norwegian': 34, 'Spanish': 30, 'Portuguese': 29, 'Japanese': 23, 'Arabic': 22, 'Turkish': 20, 'Polish': 19, 'Russian': 19, 'Indonesian': 19, 'Romanian': 19, 'Chinese Traditional': 18, 'Korean': 18, 'Greek': 17, 'Hungarian': 16, 'Thai': 14, 'Czech': 14, 'Slovak': 13, 'Serbian': 13, 'Icelandic': 9, 'Flemish': 8, 'French (Belgium)': 8, 'English (Australia)': 7, 'Latvian': 7, 'Lithuanian': 7, 'Estonian': 6, 'Vietnamese': 3, 'English (Canada)': 1, 'English (South Africa)': 1, 'Malay': 1})

In [43]:
normalized_df["duration_minutes"].describe()

count    293.000000
mean      13.607509
std        9.941931
min        0.000000
25%        8.000000
50%       10.000000
75%       16.000000
max       60.000000
Name: duration_minutes, dtype: float64

In [44]:
from collections import Counter

# Category distribution
category_counter = Counter()
for categories in normalized_df["keys"]:
    category_counter.update(categories)

# Job level distribution
job_counter = Counter()
for levels in normalized_df["job_levels"]:
    job_counter.update(levels)

# Language distribution
language_counter = Counter()
for langs in normalized_df["languages"]:
    language_counter.update(langs)

profile = {
    "total_assessments": len(normalized_df),
    "assessment_categories": dict(category_counter),
    "job_levels": dict(job_counter),
    "languages": dict(language_counter),
    "average_duration": normalized_df["duration_minutes"].mean(),
    "minimum_duration": normalized_df["duration_minutes"].min(),
    "maximum_duration": normalized_df["duration_minutes"].max()
}

profile

{'total_assessments': 377,
 'assessment_categories': {'Ability & Aptitude': 32,
  'Assessment Exercises': 2,
  'Biodata & Situational Judgment': 17,
  'Competencies': 19,
  'Development & 360': 7,
  'Personality & Behavior': 67,
  'Knowledge & Skills': 240,
  'Simulations': 43},
 'job_levels': {'Director': 55,
  'Entry-Level': 114,
  'Executive': 55,
  'General Population': 45,
  'Graduate': 140,
  'Manager': 117,
  'Mid-Professional': 304,
  'Front Line Manager': 75,
  'Supervisor': 73,
  'Professional Individual Contributor': 296},
 'languages': {'English (USA)': 321,
  'English International': 74,
  'English (Australia)': 7,
  'English (Canada)': 1,
  'English (South Africa)': 1,
  'French (Canada)': 37,
  'Portuguese (Brazil)': 37,
  'Dutch': 45,
  'Italian': 47,
  'Spanish': 30,
  'French': 50,
  'Latin American Spanish': 51,
  'Chinese Simplified': 45,
  'Chinese Traditional': 18,
  'Danish': 36,
  'Finnish': 37,
  'German': 41,
  'Icelandic': 9,
  'Polish': 19,
  'Swedish': 35,
  'Norwegian': 34,
  'Russian': 19,
  'Arabic': 22,
  'Korean': 18,
  'Indonesian': 19,
  'Thai': 14,
  'Japanese': 23,
  'Romanian': 19,
  'Vietnamese': 3,
  'Portuguese': 29,
  'Turkish': 20,
  'Latvian': 7,
  'Flemish': 8,
  'French (Belgium)': 8,
  'Greek': 17,
  'Hungarian': 16,
  'Czech': 14,
  'Slovak': 13,
  'Estonian': 6,
  'Lithuanian': 7,
  'Serbian': 13,
  'Malay': 1},
 'average_duration': np.float64(13.607508532423209),
 'minimum_duration': np.float64(0.0),
 'maximum_duration': np.float64(60.0)}

In [45]:
import json
import os

# Create reports folder if it doesn't exist
os.makedirs("../reports", exist_ok=True)

with open("../reports/dataset_profile.json", "w", encoding="utf-8") as f:
    json.dump(profile, f, indent=4)

print("Dataset profile saved successfully!")

Dataset profile saved successfully!